module: AWSSDKSwift
author: Yuki Takei
sourcekitten_sourcefile: awssdkswift-sourcekitten-doc.json
author_url: https://github.com/noppoMan
github_url: https://github.com/noppoMan/aws-sdk-swift
copyright: '© Copyright (c) 2017 Yuki Takei(noppoMan)'
theme: fullwidth
custom_categories:

  - name: Acm Client
    children:
      - Acm
      - AcmError

  - name: Apigateway Client
    children:
      - Apigateway
      - ApigatewayError

  - name: ApplicationAutoscaling Client
    children:
      - ApplicationAutoscaling
      - ApplicationAutoscalingError

  - name: Appstream Client
    children:
      - Appstream
      - AppstreamError

  - name: Athena Client
    children:
      - Athena
      - AthenaError

  - name: Autoscaling Client
    children:
      - Autoscaling
      - AutoscalingError

  - name: Batch Client
    children:
      - Batch
      - BatchError

  - name: Budgets Client
    children:
      - Budgets
      - BudgetsError

  - name: Clouddirectory Client
    children:
      - Clouddirectory
      - ClouddirectoryError

  - name: Cloudformation Client
    children:
      - Cloudformation
      - CloudformationError

  - name: Cloudfront Client
    children:
      - Cloudfront
      - CloudfrontError

  - name: Cloudhsm Client
    children:
      - Cloudhsm
      - CloudhsmError

  - name: Cloudsearch Client
    children:
      - Cloudsearch
      - CloudsearchError

  - name: Cloudsearchdomain Client
    children:
      - Cloudsearchdomain
      - CloudsearchdomainError

  - name: Cloudtrail Client
    children:
      - Cloudtrail
      - CloudtrailError

  - name: Codebuild Client
    children:
      - Codebuild
      - CodebuildError

  - name: Codecommit Client
    children:
      - Codecommit
      - CodecommitError

  - name: Codedeploy Client
    children:
      - Codedeploy
      - CodedeployError

  - name: Codepipeline Client
    children:
      - Codepipeline
      - CodepipelineError

  - name: Codestar Client
    children:
      - Codestar
      - CodestarError

  - name: CognitoIdentity Client
    children:
      - CognitoIdentity
      - CognitoIdentityError

  - name: CognitoIdp Client
    children:
      - CognitoIdp
      - CognitoIdpError

  - name: CognitoSync Client
    children:
      - CognitoSync
      - CognitoSyncError

  - name: Config Client
    children:
      - Config
      - ConfigError

  - name: Cur Client
    children:
      - Cur
      - CurError

  - name: Datapipeline Client
    children:
      - Datapipeline
      - DatapipelineError

  - name: Dax Client
    children:
      - Dax
      - DaxError

  - name: Devicefarm Client
    children:
      - Devicefarm
      - DevicefarmError

  - name: Directconnect Client
    children:
      - Directconnect
      - DirectconnectError

  - name: Discovery Client
    children:
      - Discovery
      - DiscoveryError

  - name: Dms Client
    children:
      - Dms
      - DmsError

  - name: Ds Client
    children:
      - Ds
      - DsError

  - name: Dynamodb Client
    children:
      - Dynamodb
      - DynamodbError

  - name: Ec2 Client
    children:
      - Ec2
      - Ec2Error

  - name: Ecr Client
    children:
      - Ecr
      - EcrError

  - name: Ecs Client
    children:
      - Ecs
      - EcsError

  - name: Elasticache Client
    children:
      - Elasticache
      - ElasticacheError

  - name: Elasticbeanstalk Client
    children:
      - Elasticbeanstalk
      - ElasticbeanstalkError

  - name: Elasticfilesystem Client
    children:
      - Elasticfilesystem
      - ElasticfilesystemError

  - name: Elasticloadbalancing Client
    children:
      - Elasticloadbalancing
      - ElasticloadbalancingError

  - name: Elasticloadbalancingv2 Client
    children:
      - Elasticloadbalancingv2
      - Elasticloadbalancingv2Error

  - name: Elasticmapreduce Client
    children:
      - Elasticmapreduce
      - ElasticmapreduceError

  - name: Elastictranscoder Client
    children:
      - Elastictranscoder
      - ElastictranscoderError

  - name: Email Client
    children:
      - Email
      - EmailError

  - name: Entitlementmarketplace Client
    children:
      - Entitlementmarketplace
      - EntitlementmarketplaceError

  - name: Es Client
    children:
      - Es
      - EsError

  - name: Events Client
    children:
      - Events
      - EventsError

  - name: Firehose Client
    children:
      - Firehose
      - FirehoseError

  - name: Gamelift Client
    children:
      - Gamelift
      - GameliftError

  - name: Glacier Client
    children:
      - Glacier
      - GlacierError

  - name: Greengrass Client
    children:
      - Greengrass
      - GreengrassError

  - name: Health Client
    children:
      - Health
      - HealthError

  - name: Iam Client
    children:
      - Iam
      - IamError

  - name: Importexport Client
    children:
      - Importexport
      - ImportexportError

  - name: Inspector Client
    children:
      - Inspector
      - InspectorError

  - name: IotData Client
    children:
      - IotData
      - IotDataError

  - name: Iot Client
    children:
      - Iot
      - IotError

  - name: Kinesis Client
    children:
      - Kinesis
      - KinesisError

  - name: Kinesisanalytics Client
    children:
      - Kinesisanalytics
      - KinesisanalyticsError

  - name: Kms Client
    children:
      - Kms
      - KmsError

  - name: Lambda Client
    children:
      - Lambda
      - LambdaError

  - name: LexModels Client
    children:
      - LexModels
      - LexModelsError

  - name: Lightsail Client
    children:
      - Lightsail
      - LightsailError

  - name: Logs Client
    children:
      - Logs
      - LogsError

  - name: Machinelearning Client
    children:
      - Machinelearning
      - MachinelearningError

  - name: Marketplacecommerceanalytics Client
    children:
      - Marketplacecommerceanalytics
      - MarketplacecommerceanalyticsError

  - name: Meteringmarketplace Client
    children:
      - Meteringmarketplace
      - MeteringmarketplaceError

  - name: Mobileanalytics Client
    children:
      - Mobileanalytics
      - MobileanalyticsError

  - name: Monitoring Client
    children:
      - Monitoring
      - MonitoringError

  - name: MturkRequester Client
    children:
      - MturkRequester
      - MturkRequesterError

  - name: Opsworks Client
    children:
      - Opsworks
      - OpsworksError

  - name: Opsworkscm Client
    children:
      - Opsworkscm
      - OpsworkscmError

  - name: Organizations Client
    children:
      - Organizations
      - OrganizationsError

  - name: Pinpoint Client
    children:
      - Pinpoint
      - PinpointError

  - name: Polly Client
    children:
      - Polly
      - PollyError

  - name: Rds Client
    children:
      - Rds
      - RdsError

  - name: Redshift Client
    children:
      - Redshift
      - RedshiftError

  - name: Rekognition Client
    children:
      - Rekognition
      - RekognitionError

  - name: Resourcegroupstaggingapi Client
    children:
      - Resourcegroupstaggingapi
      - ResourcegroupstaggingapiError

  - name: Route53 Client
    children:
      - Route53
      - Route53Error

  - name: Route53domains Client
    children:
      - Route53domains
      - Route53domainsError

  - name: Runtimelex Client
    children:
      - Runtimelex
      - RuntimelexError

  - name: S3 Client
    children:
      - S3
      - S3Error

  - name: Sdb Client
    children:
      - Sdb
      - SdbError

  - name: Servicecatalog Client
    children:
      - Servicecatalog
      - ServicecatalogError

  - name: Shield Client
    children:
      - Shield
      - ShieldError

  - name: Sms Client
    children:
      - Sms
      - SmsError

  - name: Snowball Client
    children:
      - Snowball
      - SnowballError

  - name: Sns Client
    children:
      - Sns
      - SnsError

  - name: Sqs Client
    children:
      - Sqs
      - SqsError

  - name: Ssm Client
    children:
      - Ssm
      - SsmError

  - name: States Client
    children:
      - States
      - StatesError

  - name: Storagegateway Client
    children:
      - Storagegateway
      - StoragegatewayError

  - name: Streamsdynamodb Client
    children:
      - Streamsdynamodb
      - StreamsdynamodbError

  - name: Sts Client
    children:
      - Sts
      - StsError

  - name: Support Client
    children:
      - Support
      - SupportError

  - name: Swf Client
    children:
      - Swf
      - SwfError

  - name: WafRegional Client
    children:
      - WafRegional
      - WafRegionalError

  - name: Waf Client
    children:
      - Waf
      - WafError

  - name: Workdocs Client
    children:
      - Workdocs
      - WorkdocsError

  - name: Workspaces Client
    children:
      - Workspaces
      - WorkspacesError

  - name: Xray Client
    children:
      - Xray
      - XrayError
