language: generic
matrix:
  include:
    - os: linux
      services: docker
      before_install:
        - docker pull swift:5.1.1
      install:
        - source scripts/localstack.sh start
      script:
        - docker run --network=host -v "$(pwd):/root/aws-sdk-swift" swift:5.1.1 /bin/sh -c "apt-get -qq update && apt-get -q -y install tzdata libssl-dev zlib1g-dev && cd /root/aws-sdk-swift && swift test --parallel -Xswiftc -DDEBUG"
    - os: osx
      language: swift
      osx_image: xcode11
      script:
        - swift build
