name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  macos:
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: SPM build
      run: swift build

  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ['swift:5.1', 'swift:5.2']
    services:
      localstack:
        image: localstack/localstack
        options: >-
          --workdir /opt/code/localstack/
    container:
      image: ${{ matrix.image }}
      env:
        APIGATEWAY_ENDPOINT : "http://localstack:4567"
        DYNAMODB_ENDPOINT   : "http://localstack:4569"
        IAM_ENDPOINT        : "http://localstack:4593"
        S3_ENDPOINT         : "http://localstack:4572"
        SNS_ENDPOINT        : "http://localstack:4575"
        SQS_ENDPOINT        : "http://localstack:4576"
        SSM_ENDPOINT        : "http://localstack:4583"
        STS_ENDPOINT        : "http://localstack:4592"
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install dependencies
      run: |
        apt-get update -qq
        apt-get install -q -y tzdata zlib1g-dev
    - name: Test
      run: swift test -Xswiftc -DDEBUG
