name: Generate Documentation

on:
  push:
    branches:
      - "gen-docs-on-release"

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install Jazzy
      run: gem install jazzy
    - name: Build
      run: |
        cd jazzy
        node create-jazzy.yaml.js
        cd ..
    - name: Commit
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REMOTE_BRANCH: "gh-pages"
      run: |
        REMOTE_REPO="https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

